### ISSUE TITLE
[Bug?] alien_value_threshold used by Peeler but not by CatalogWindow

### ISSUE THREAD

**Issue by jpgill86** [tridesclous/tridesclous#101]
**How to reproduce:** In [`example_locust_dataset.ipynb`](https://github.com/tridesclous/tridesclous/blob/master/example/example_locust_dataset.ipynb), set `alien_value_threshold` to a value lower than `relative_threshold`, like 5.0.

**What I expected:** When the CatalogueWindow launches so that the user can check the clusters, spikes above the `alien_value_threshold` (in this case, all spikes) should have cluster label "-9 (Alien)". The "real" clusters should be empty.

**What happens instead:** The alien cluster is empty and spikes fill the "real" clusters.

In one sense, this is not very surprising since `find_clusters` is called after `clean_waveforms` and relabels all the spikes. What I find puzzling is that the Peeler still knows about the original alien threshold and uses it, so the Peeler finds no spikes.

When using tridesclous on my own data, I accidentally increased the `relative_threshold` to the same value as the default `alien_value_threshold`. When I launched the CatalogueWindow, I saw lots of clusters that I liked. When I ran the Peeler, I got nothing! I was very confused until I discovered that I had `relative_threshold = alien_value_threshold`. I fixed this mistake, but it is still the case that the CatalogueWindow shows spikes that exceed `alien_value_threshold` and which will be excluded by the Peeler. This seems like a bug.

EDIT: Note that it is not possible to just reverse the order in which `find_clusters` and `clean_waveforms` are called since `clean_waveforms` [resets all other cluster labels to 0](https://github.com/tridesclous/tridesclous/blob/4c821c6db00744195481ff61bb937ddba1ac396b/tridesclous/catalogueconstructor.py#L747).

**Comment by samuelgarcia** [comment]
Yes there was a bug around alien_threshold.
I think it is corrected in #102.
Could you test ?

The corrected behavior is that "alien" spikes are not used in projection (pca) nor in cluster because it biase a lot. In some case the label was reset to 0 and so the alien label was lost. I hope it has disappear.
