### ISSUE TITLE
GUI crashes after spike export

### ISSUE THREAD

**Issue by ludo67100** [tridesclous/tridesclous#111]
Hi Sam, 

Here is the issue I had with tridesclous. After running the catalogue and the peeler, I want to export the spike indexes (csv or xlsx). 

I click on export spikes with following options : 
![image](https://user-images.githubusercontent.com/44300957/54222594-051de680-44f6-11e9-9c18-96a31812ea3c.png)

The spikes are in deed exported, the files are ok, but the UI vanishes, here is the Traceback : 
![image](https://user-images.githubusercontent.com/44300957/54222746-54641700-44f6-11e9-9910-5b574f5761d6.png)

Hope you'll find something, 

See you soon camarade ! 

Ludo

**Comment by pplenck** [comment]
I do have the same issue
I cannot save at all actually.
same exact errors:

"  File "c:\programdata\anaconda2\envs\tridesclous\lib\site-packages\tridesclous\gui\mainwindow.py", line 543, in export_spikes
    split_by_cluster=p['split_by_cluster'],  use_cell_label=p['use_cell_label'], formats=p['format'])
  File "c:\programdata\anaconda2\envs\tridesclous\lib\site-packages\tridesclous\dataio.py", line 654, in export_spikes
    spikes = self.get_spikes(seg_num=seg_num, chan_grp=chan_grp)
  File "c:\programdata\anaconda2\envs\tridesclous\lib\site-packages\tridesclous\dataio.py", line 544, in get_spikes
    spikes = self.arrays[chan_grp][seg_num].get('spikes')
  File "c:\programdata\anaconda2\envs\tridesclous\lib\site-packages\tridesclous\iotools.py", line 279, in get
    assert name in self._array_attr
AssertionError "
this is a raw copy/paste

Help?

**Comment by samuelgarcia** [comment]
I will fix this soon.
For now, you must compute all channel groups before export.

**Comment by samuelgarcia** [comment]
Done in #PR 113.
