### ISSUE TITLE
Feature request: implement bad channels

### ISSUE THREAD

**Issue by subhacom** [tridesclous/tridesclous#136]
There seem to be no way to tell DataIO or CatalogConstructor that some channels are bad. It can happen that only after loading and plotting the data the user notices odd noise in some channels and wants to exclude them from further processing.

It is not clear if there is a way to do this in current version of tridesclous. The only way (for custom formats) seems to be to regenerate the dataset without the data from the bad channels, and to edit the probe file changing the channel indices, and running through the whole process again. 

A parameter/attribute to specify bad channels for exclusion from analysis will reduce this burden.

**Comment by samuelgarcia** [comment]
The bad channel feature is implemented with the PRB file system.
You can add a second chan_grp that do not contain the bad channel and rerun everything.
You od ont need make another folder for that.

I guess you the regeneration is due to the fact that you are using spiekinterface.

If you bypass SI then you can play nicely with the internal PRB without any copy.

**Comment by subhacom** [comment]
So I figured that the bad channel is implemented by skipping the index of the bad channel in the list of channels in the probe file. Thus, if the first channel of the tetrode is bad, this is how the probe file should look:
```python

# The channel numbers here are used as channel indices in the 2D data array
# - column index in Tridesclous/neo/klusta but row index in 
# SpikeInterface NumpyRecordingExtractor

total_nb_channels = 4   # SpykingCircus uses this parameter
radius = 50                    # SpykingCircus applies the templates for a probe over this spatial extent 
channel_groups = {
     0: 
        {
#           'channels': [0, 1, 2, 3],   # if all channels were to be used in spike-sorting
           'channels': [1, 2, 3],   # do not use data from channel 0
           'graph':  [],  # Used by klusta but we don't care, SpikeInterface fills this up automatically
           'geometry':  {
              # 0: [0, 20],
               1: [0, -20],
               2: [20, 0],
               3: [-20, 0],
           }
       },
}
```
It will be useful to add this in the documentation, as it takes some effort to figure this out.
