### ISSUE TITLE
Can't open tridesclous GUI

### ISSUE THREAD

**Issue by Shivooone** [tridesclous/tridesclous#165]
Hello,

I would like to open up tridesclous GUI (I followed all the installation process). I created a new env in conda, containing tridesclous, and ran 'source activate tdc' both in my nez conda environment and base terminal and get this

![1](https://user-images.githubusercontent.com/82379695/115558312-e7b1ce00-a2b2-11eb-8b8a-43bd2f55ce5b.PNG)

I would be very grateful for your help, I really don't figure out whats wrong.

**Comment by samuelgarcia** [comment]
In windows you only have to do
```
activate tdc
# check that name inside parenthesis change
tdc
```
