### ISSUE TITLE
QT5 issue

### ISSUE THREAD

**Issue by timsainb** [tridesclous/tridesclous#167]
Hey All,

I'm having trouble running tridesclous on my compute server. It gives this error:

Cannot load backend 'Qt5Agg' which requires the 'qt5' interactive framework, as 'headless' is currently running. You can inspect the runtime trace in the tridesclous.log of the output folder.'`

Any idea what's going on? Why does tridesclous run through spikeinterface care at all about qt5 or matplotlib? 

Thanks,
Tim

**Comment by samuelgarcia** [comment]
Hi Tim,
normally this is already fix in the latest release.
Please upgrade and tell me if it is fixed.

**Comment by timsainb** [comment]
Running on the current master branch and still get this issue. It comes after `compute_cluster_centroid`

**Comment by samuelgarcia** [comment]
Hi.
Thanks for feedback.
Normally the tridesclous core do not import anymore matplotlib or Qt5.
Maybe I forgot something.
Could you send me your code and the full error trace ?

**Comment by timsainb** [comment]
Looks like it worked!
