### ISSUE TITLE
example test: set parameters error

### ISSUE THREAD

**Issue by vncntprvst** [tridesclous/tridesclous#27]
I know this is a work in progress but while testing the example code in jupyter, running this step:
`catalogueconstructor.set_preprocessor_params(chunksize=1024,
            common_ref_removal=False,
            highpass_freq=300.,
            backward_chunksize=1280,
            peak_sign='-',
            relative_threshold=7,
            peak_span=0.0005,
            )
`

returns this error:

`TypeError                                 Traceback (most recent call last)
<ipython-input-11-ad8ebbfe5121> in <module>()
      5             peak_sign='-',
      6             relative_threshold=7,
----> 7             peak_span=0.0005,
      8             )

TypeError: set_preprocessor_params() got an unexpected keyword argument 'backward_chunksize'
`

**Comment by samuelgarcia** [comment]
Is is already corrected here https://github.com/samuelgarcia/tridesclous
clone from there if you want really up to date.
Will merge soon.

**Comment by vncntprvst** [comment]
Great! Thanks

**Comment by vncntprvst** [comment]
I uninstalled tridesclous then re-installed from your repository, started a new notebook but still got this error message. 
`TypeError: set_preprocessor_params() got an unexpected keyword argument 'backward_chunksize'`

**Comment by samuelgarcia** [comment]
You need to also take the new jupyter  notebook from there.
Now the kargs is lostfront_chunksize=64.

See https://github.com/samuelgarcia/tridesclous/blob/master/example/example_locust_dataset.ipynb

**Comment by vncntprvst** [comment]
I see. Sounds good.
