### ISSUE TITLE
exporting results

### ISSUE THREAD

**Issue by vncntprvst** [tridesclous/tridesclous#29]
Hi,
First, I want to congratulate you on the great job you did here. Both Method 1 and 2 (haven't tried Method 3) are easy to follow and user friendly. 
This is not so much an issue as a feature request. The documentation does not guide the user about how to use the results (after the "peeling" process). All results files are in binary format. The notebook example includes lines such as `spikes = dataio.get_spikes(seg_num)`, but it would be nice to have a simple method to recover spike labels, timestamps and waveforms. Ideally, an export function would be available in the PeelerWindow GUI. 
Thanks!

**Comment by samuelgarcia** [comment]
Thank you for this feed back.
The documentation is clearly a weakness, I am currently working a bit on it. But my english is so bad that it take to me very long time. Any help is welcome to for proof read!!

For the output, nothing is done at the moment. I will try write some file output to standard ones (kiwk,  .mat, txt, phy-template, ...) and also some convenient methods.

For the moment, the only way is this poor approach
```python
spikes = dataio.get_spikes(seg_num)
labels = np.unique(spikes['label'])
for label in label:
    mask = spikes['label'] == label
    spike_times = spikes['index'][mask] / sample_rate
```

**Comment by vncntprvst** [comment]
OK, thanks, I'll try that. 
We can help with proofreading.

**Comment by samuelgarcia** [comment]
I don't knwon if you are still trying tridesclous.
Doc, algos and GUI have been improved a lot since last 2 weeks.

Any feed back on the doc is welcome :)

Export is not done yet.

best

**Comment by vncntprvst** [comment]
Thanks for the update. I just gave it a try. Will comment in a separate thread.

**Comment by vncntprvst** [comment]
The documentation is indeed greatly improved! We just need the "parameters" page now :) Then, adding a few user cases with different types of data, and optimal parameters, would be great ^^

**Comment by vncntprvst** [comment]
Also, don't forget to fill the release notes. It helps keeping track of developments, bug fixes and new features.
