### ISSUE TITLE
SC import

### ISSUE THREAD

**Issue by yger** [tridesclous/tridesclous#38]
This is currently not properly working, because some changes have to be made L34

assert config['data']['file_format'] == 'raw_binary', 'only  RAWBINARY supported'
          
and L137     

N_t = config.getfloat('detection', 'N_t')

Note also, that L41 is wrong, or deprecated. We do not use 'MCS' for data_offset anymore, the file format for MCS is now mcs_raw_binary, and the header is more complicated that just a fixed offset, as the size can vary from file to files.

**Comment by samuelgarcia** [comment]
C'est balo.

T'as du code pour trouver le byteoffset du mcs_raw_binary ?

**Comment by yger** [comment]
Allez va, parce que c'est toi

[test.txt](https://github.com/tridesclous/tridesclous/files/1482495/test.txt)

**Comment by yger** [comment]
Si tu charges mal les données, ca va pas marcher.... offset est ce qui t'intéresse, c'est juste pour les mcs_raw_binary

**Comment by samuelgarcia** [comment]
Yep merci.
Je patch ça tantôt. Avec re ça prendrait pas une ligne ton truc ?

**Comment by yger** [comment]
Si, surement, feel free to enhance. Il faut juste chercher le motif EOH (End Of Header) et ensuite, les data commencent.

**Comment by samuelgarcia** [comment]
Avec ça c'est plus la classe:
```python
        import re
        with open(data_filename, 'rb') as f:
            header = f.read(5000).decode('Windows-1252')
        data_offset = re.search("EOH", header).start() + 3
```

Par contre je trouve 1864 et depuis le debut je code en dur 1866 pour tes fichiers.
Comment est ce possible ?

**Comment by samuelgarcia** [comment]
J epense qu'il manque 2 dan ton example (et du coup dans le miens aussi) car à la fin du header il y a
b'\r\n' qui ne font pas encore parti des data. Du coup on  1866.

Donc en  fait ce serait:
```python
        import re
        with open(data_filename, 'rb') as f:
            header = f.read(5000).decode('Windows-1252')
        data_offset = re.search("EOH", header).start() + 3  + 2
```

**Comment by yger** [comment]
Ça je sais pas, moi le code que je t'ai donné marche, c'est tout ce que je
sais. La taille du byteoffset varie en fonction des fichiers, aux alentours
de ces valeurs, donc regarde juste si ce que tu charges à du sens ou pas

Le sam. 18 nov. 2017 à 16:50, Garcia Samuel <notifications@github.com> a
écrit :

**Comment by yger** [comment]
Sinon tu regardes le fichier circus/files/mcs_raw_binary.py

**Comment by samuelgarcia** [comment]
As tu testé le patch ? Pour je ferme cet issue.
