### ISSUE TITLE
Choosing parameters

### ISSUE THREAD

**Issue by vncntprvst** [tridesclous/tridesclous#44]
At the moment, that page in the documentation is empty.

Quick question on that topic, what is the unit for n_left and n_right parameters for waveform extraction? data samples, or milliseconds?

Thanks

**Comment by samuelgarcia** [comment]
Oups. My lazyness have been discovered.
I will do it very soon.

n_left and n_right are in sample. n_left is negative. 0 is the peak.

Maybe I could put a sweep_left/sweep_right in ms for the GUI that would be internaly converted to n_left/n_right.

**Comment by vncntprvst** [comment]
ok, thanks!
