### ISSUE TITLE
Mailing list, feature request protocol?

### ISSUE THREAD

**Issue by MisterVulcan** [tridesclous/tridesclous#52]
Hello; this is not a technical issue, but I wanted to ask if you have a mailing list for tdc or anywhere else that could be used to communicate with the developers about possible feature requests, or just asking questions about the project that aren't mentioned in the documentation yet. My lab is migrating from klustakwik/phy to tdc and I am also interested in being a guinea pig/beta tester if it is currently under active development. Thanks!

**Comment by samuelgarcia** [comment]
Dear MisterVulcan,
thank you for having attention on tdc and trying it.

I prefer to not have mailing list for the moment.
User community size quite small now and V1.0 is not released yet.
Here in github issue is the good place for feautre request.
Open as many issue as you want I would happy to discuss them.

The project is under acttive deleopement even if there is a small pause of 2 mouth dut to other projects.

best

Samuel

**Comment by MisterVulcan** [comment]
Good to know, I'll put together a list.
