### ISSUE TITLE
On-the-loop peak curation from another program

### ISSUE THREAD

**Issue by MisterVulcan** [tridesclous/tridesclous#58]
This is more a technical question than an issue, so I'll close it once I get it figured out unless someone wants to keep it for posterity.

My experimental setup involves tracking test subjects during recordings, so there's an (X,Y) coordinate pair corresponding to every spike in every cluster in the catalogue (some binning involved, but not relevant) after sorting and running `peeler`. I've written some code that plots the 2D-spatial coordinates of all spikes in a cluster as data points, with the ability to select individual or groups of spikes based on their location. All information regarding a single data point (spike), including it's timestamp, segment number, spatial coordinates, and what unit cluster it belongs to, are stored in a `pandas` `DataFrame` for easy access.

What I'd like to do, using the selection tool, is modify a `catalogueconstructor`'s list of classified spikes to only include those that have been selected from the coordinate map. This would allow me to further refine clustering results to focus on spikes based on their location. The simplest way I can think of is to somehow move all spikes except those selected in the location map plot to the `-10 unclassified` cluster. I have ready access to timestamps and segment #'s for all of the classified spikes in a catalogue; I just need a way to edit the catalogue's clusters by matching up the spikes selected in the location plot to those in the catalogue. I'd like to avoid digging through source code if possible, so any suggestions? Gracias.

**Comment by samuelgarcia** [comment]
If understand corrctly you want to hack the catalogue to keep only cluster that have a clear receptor field.
So yes this is teh good approach:
  * Send to trash all clusetr you don't want in the catalogue.
  * Do again agin make_catalogue_for_peeler
  *  and re run the peeler.

Spike that do nto match any template should be unclassified.

I guess you want to do it with a script.
this should look like this
```python
import tridesclous as tdc

# this script start when a full job have already been done.

dataio = tdc.DataIO(dirname='/path/to/my_tdc_dir')
cc = tdc.CatalogueConstructor(dataio=dataio, chan_grp=0) # put the good chan group here

# move each peak you do not want to trash
list_of_label_to_remove = [12, 16, 38, 168]
for k in list_of_label_to_remove:
    mask = (cc.clusters['cluster_label'] == k)
    cc.controller.change_spike_label(mask, -1)

# re make the catalogue with cleaned centroids
cc.make_catalogue_for_peeler()

# re run peeler
initial_catalogue = dataio.load_catalogue(chan_grp=0)
peeler = tdc.Peeler(dataio)
peeler.change_params(catalogue=initial_catalogue)
peeler.run(progressbar=True)


```

**Comment by MisterVulcan** [comment]
That's pretty much it - sorry I didn't realize that the locust dataset notebook addresses this.

**Comment by samuelgarcia** [comment]
Can I close this ?
