### ISSUE TITLE
Example notebook needs to be updated

### ISSUE THREAD

**Issue by jchutrue** [tridesclous/tridesclous#66]
I attempted to run example_locust_dataset.ipynb but it looks like several things in the notebook are incompatible with the latest version of tridesclous. For example, I got errors such as 
`TypeError: set_preprocessor_params() got an unexpected keyword argument 'lowpass_freq'`
 and  `AttributeError: 'CatalogueConstructor' object has no attribute 'extract_some_features'`

**Comment by samuelgarcia** [comment]
Yep that is true I updated some function in CatalogueConstructor without changing example.
I will fix this.
Thanks.

**Comment by jchutrue** [comment]
Thank you! Definitely want to try it out on my data.

**Comment by samuelgarcia** [comment]
You can try with the GUI for a first overview.

**Comment by jchutrue** [comment]
I tried to launch the GUI by typing `tdc` in a terminal, per the documentation, but it didn't work. I assume I need to add the right path, or maybe I'm starting it up incorrectly?

**Comment by samuelgarcia** [comment]
What error message do you have ?

**Comment by jchutrue** [comment]
Ahh! I hadn't activated my conda environment. That did the trick.

**Comment by samuelgarcia** [comment]
Done in #68
